<?php
namespace Pbxg33k\UtorrentClient\Model;

use Doctrine\Common\Collections\ArrayCollection;

class RssFeed extends BaseModel
{
    /**
     * @var int
     */
    protected $id;
    /**
     * @var bool
     */
    protected $enabled;
    /**
     * @var bool
     */
    protected $useFeedTitle;
    /**
     * @var bool
     */
    protected $userSelected;
    /**
     * @var bool
     */
    protected $programmed;
    /**
     * @var int
     */
    protected $downloadState;
    /**
     * @var string
     */
    protected $url;
    /**
     * @var int
     */
    protected $nextUpdate;
    /**
     * @var ArrayCollection
     */
    protected $items;

    protected $map = [
        "id" => 0,
        "enabled" => 1,
        "useFeedTitle" => 2,
        "userSelected" => 3,
        "programmed" => 4,
        "downloadState" => 5,
        "url" => 6,
        "nextUpdate" => 7,
    ];

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function fromJson($json)
    {
        parent::fromJson($json);

        foreach($json[8] as $item) {
            $this->items->add((new RssItem())->fromJson($item));
        }

        return $this;
    }

    public function toOriginal()
    {
        $returnObj = parent::toOriginal(); // TODO: Change the autogenerated stub
        $items = [];
        /** @var RssItem $item */
        foreach($this->items as $item) {
            $items[] = $item->toOriginal();
        }
        $returnObj[] = $items;

        return $returnObj;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return bool
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @return bool
     */
    public function getUseFeedTitle(): bool
    {
        return $this->useFeedTitle;
    }

    /**
     * @return bool
     */
    public function getUserSelected(): bool
    {
        return $this->userSelected;
    }

    /**
     * @return bool
     */
    public function getProgrammed(): bool
    {
        return $this->programmed;
    }

    /**
     * @return int
     */
    public function getDownloadState(): int
    {
        return $this->downloadState;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @return int
     */
    public function getNextUpdate(): int
    {
        return $this->nextUpdate;
    }

    /**
     * @return ArrayCollection
     */
    public function getItems(): ArrayCollection
    {
        return $this->items;
    }

    /**
     * @return array
     */
    public function getMap(): array
    {
        return $this->map;
    }
}